-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/DownloadBook/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bookrenderingtask (
  brt_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  brt_timestamp VARBINARY(14) NOT NULL,
  brt_state VARCHAR(32) NOT NULL,
  brt_disposition VARCHAR(255) DEFAULT NULL,
  brt_stash_key VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY(brt_id)
) /*$wgDBTableOptions*/;
